FILES = \
	main.cpp \
	helpers.cpp \
	/home/jonathan/Documents/code/c++/teamsDLL/libteams.so #path to library. I could not get it to work without direct path for some reason.

all:
	g++ ${FILES} -o test